from yacs.config import CfgNode as CN

_C = CN()

_C.DATA = CN()
_C.DATA.SET = 'ImageNet'
_C.DATA.ROOT = 'datasets'
_C.DATA.NUM_WORKER_PROCESSES = 1
_C.DATA.BATCH_SIZE = 256
_C.DATA.DROP_LAST = True

_C.OPTIMIZER = CN()
_C.OPTIMIZER.METHOD = 'SGD'
_C.OPTIMIZER.LR = 0.1
_C.OPTIMIZER.WEIGHT_DECAY = 0.0005
_C.OPTIMIZER.L1_REG_STRENGTH = 0.0005

_C.OPTIMIZER.SGD = CN()
_C.OPTIMIZER.SGD.MOMENTUM = 0.9
_C.OPTIMIZER.SGD.NESTEROV = False

_C.SCHEDULER = CN()
_C.SCHEDULER.METHOD = 'warm_up'
_C.SCHEDULER.MILESTONES = (0, )
_C.SCHEDULER.GAMMA = 0.1

_C.MODEL = CN()
_C.MODEL.HALF_PRECISION = True
_C.MODEL.META = 'KD'
_C.MODEL.STUDENT = 'R18'
_C.MODEL.TEACHER = 'I-R50'
_C.MODEL.LOSS = 'KnowlegeDistillationLoss'

_C.ENGINE = CN()
_C.ENGINE.MAX_EPOCHS = 100


_C.CHECKPOINT = CN()
_C.CHECKPOINT.SAVE_INTERVAL = 5
_C.CHECKPOINT.N_SAVED = 20

_C.LOGGING_TERM = 20

cfg = _C
